# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  use_frameworks!
 pod 'FBSDKLoginKit'
 pod 'FacebookCore'
 pod 'FacebookLogin'
 pod 'FacebookShare'
 pod 'Unbox'
  # Pods for FBLogin

  target 'FBLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
